### ISSUE TITLE
S3ResponseError: S3ResponseError: 400 Bad Request when using V1.12.0

### ISSUE THREAD

**Issue by azagniotov** [qubole/qds-sdk-py#277] opened 2019-06-10 21:14 UTC
**TL;DR**
`S3ResponseError: S3ResponseError: 400 Bad Request ` when making `hivecmd getresult` command using `V1.12.0`. This behavior does not happen with I build & install earlier releases `V1.11.1` and `V1.11.0`.

**Longer version**
I have built & installed `V1.12.0` from the release branch and tried to execute the following `hivecmd getresult` command:
```
/usr/local/bin/qds.py --token=<TOKEN>  --url=https://<QUBOLE_HOST>/api  -vv hivecmd getresult <COMMAND_ID>  > results.txt
```
I got `S3ResponseError: S3ResponseError: 400 Bad Request`. 

Please refer below to the full error output:
```
INFO:qds_connection:[GET] https://<QUBOLE_HOST>/api/v1.2/commands/<COMMAND_ID>
INFO:qds_connection:Payload: null
INFO:qds_connection:Params: None
INFO:qds:Fetching results for HiveCommand, Id: <COMMAND_ID>
INFO:qds_connection:[GET] https://<QUBOLE_HOST>/api/v1.2/commands/<COMMAND_ID>/results
INFO:qds_connection:Payload: null
INFO:qds_connection:Params: {'include_headers': 'false', 'inline': True}
INFO:qds_connection:[GET] https://<QUBOLE_HOST>/api/v1.2/accounts/get_creds
INFO:qds_connection:Payload: null
INFO:qds_connection:Params: None
INFO:qds_commands:Starting download from result locations: [s3://<S3_HOST>/account_id/<ACCOUNT_ID>/tmp/<DATE>/<ACCOUNT_ID>/<COMMAND_ID>,s3://<S3_HOST>/account_id/<ACCOUNT_ID>/tmp/<DATE>/<ACCOUNT_ID>/<COMMAND_ID>.dir/]
INFO:qds_connection:[GET] https://<QUBOLE_HOST>/api/v1.2/commands/<COMMAND_ID>
INFO:qds_connection:Payload: null
INFO:qds_connection:Params: None
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qds_sdk-1.12.0-py2.7.egg/EGG-INFO/scripts/qds.py", line 690, in <module>
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qds_sdk-1.12.0-py2.7.egg/EGG-INFO/scripts/qds.py", line 637, in main
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qds_sdk-1.12.0-py2.7.egg/EGG-INFO/scripts/qds.py", line 225, in cmdmain
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qds_sdk-1.12.0-py2.7.egg/EGG-INFO/scripts/qds.py", line 191, in getresultaction
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qds_sdk-1.12.0-py2.7.egg/EGG-INFO/scripts/qds.py", line 130, in _getresult
  File "build/bdist.macosx-10.12-x86_64/egg/qds_sdk/commands.py", line 327, in get_results
    _download_to_local(boto_conn, s3_path, fp, num_result_dir, delim=delim)
  File "build/bdist.macosx-10.12-x86_64/egg/qds_sdk/commands.py", line 1432, in _download_to_local
    bucket = boto_conn.get_bucket(bucket_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/boto-2.49.0-py2.7.egg/boto/s3/connection.py", line 509, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/boto-2.49.0-py2.7.egg/boto/s3/connection.py", line 556, in head_bucket
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 400 Bad Request
```

**Comment by chattarajoy** [comment] 2019-06-11 06:33
Thanks @azagniotov for informing us about the issue. Could you please share the command id and qubole environment so that we can investigate this?

I feel this has got something to do with the recent v4 signature change we had pushed in the above version. However, it works fine for our S3 buckets.

**Comment by azagniotov** [comment] 2019-06-11 15:27
@chattarajoy Hello. 

I am not sure what you mean by `Qubole environment`. The version of Qubole? Do you mean the`QDS Version`? I see that it is `55.0.55`. 

Regarding the command ID, I prefer not to share it here in public. That said, I have observed the `400` error behavior with different commands, not only a specific one.

**Comment by chattarajoy** [comment] 2019-06-11 16:13
By Qubole environment I was actually referring to the API url.

Regarding the command id, in that case could you please create a support
ticket with Qubole along with all the details.

**Comment by azagniotov** [comment] 2019-06-11 16:31
@chattarajoy I cannot disclose the API URL as it is a specific subdomain allocated to my employer. I do not think I should be raising a support ticket with Qubole, as this has nothing to do with the command itself. 

My issue has to do with the SDK version `V1.12.0` and as you pointed out, maybe this has to do with the recent v4 signature change. By looking at the differences between `V1.12.0` and `V1.11.1`, it looks like that's the biggest change. I do not think I can help you beyond the information I have already provided to you.

**Comment by chattarajoy** [comment] 2019-06-11 17:38
@azagniotov the reason I asked you to create a support ticket is that we will need more details so that we can reproduce this on our end. Details like bucket name and location are essential here.

I agree this is completely related to the sdk version, but the qds-sdk is maintained by qubole engineering team (that is us). Please create a support ticket (this is just to get the details which cannot be shared on a public platform) and reference this conversation, the issue will be forwarded to our team eventually. This will be of great help in resolving this issue at the earliest.

**Comment by azagniotov** [comment] 2019-06-11 18:28
@chattarajoy Done. Subject of the support ticket is the same as the current GitHub issue

**Comment by chattarajoy** [comment] 2019-06-11 19:06
Thanks a lot @azagniotov . Will update you once we have a resolution, till then please use the older version of the sdk

**Closed** 2020-10-19 13:02 UTC

**Comment by azagniotov** [comment] 2020-10-19 20:38
Hi @chattarajoy,

Could you please provide an update on this?
